
name: Pull Request Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

  notify-discord:
    name: 📣 Notify Discord
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: 📤 Send message to Discord
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -X POST "$DISCORD_WEBHOOK" \-H "Content-Type: application/json" \-d '{"content": "✅ Build passed for PR #${{ github.event.pull_request.number }} by ${{ github.actor }} in ${{ github.repository }}.\n🔗 ${{ github.event.pull_request.html_url }}"}'
