name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build
        run: echo "Здесь твоя сборка"

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Send Discord Notification
        run: |
          STATUS=${{ needs.build.result }}
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \":bell: PR Build finished with status **$STATUS**\"}" \
               ${{ secrets.DISCORD_HOOK }}
